//  INTRO / SETUP
// GET REQUESTS
// ROUTE PARAMETERS
// QUERY PARAMETERS
// POST REQUESTS
// PATCH REQUESTS
// PUT REQUESTS
// DELETE REQUESTS
// MIDDLEWARE
// VALIDATION
// ROUTES
// COOKIES
// SESSIONS
// PASSPORT
// DATABASES
// HASH PASSWORDS
// SESSION STORE
// OAUTH/ AUTHENTICATION
// UNIT TESTING WITH JEST
// E2E TESTING WITH SUPER-TEST
